amazon.aws.ec2:
  key_name: heena
  instance_type: t2.micro
  image: ami-0489c6c0a2c0b6281
  wait: 'yes'
  group: qa-featurebase
  count: 1
  vpc_subnet_id: subnet-03813c401556fd63c
  assign_public_ip: 'yes'
  instance-tags:
    Name: TestHH

